### PR TITLE
[16.0] [MIG] School Evaluation

### PR DESCRIPTION
**Pull request by Rajan-SCS**

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
What's expected from you and @AnuKPatel at this stage is: SMART EVALUATION yourself for the module, rather than module itself.
Cannot you think of https://github.com/odoo/odoo/tree/16.0/addons/rating module, official one?

**Comment by AnuKPatel** [comment]
> What's expected from you and @AnuKPatel at this stage is: SMART EVALUATION yourself for the module, rather than module itself. Cannot you think of https://github.com/odoo/odoo/tree/16.0/addons/rating module, official one?

@JayVora-SerpentCS We are using the rating module from v15 itself. Removed the custom code.

**Comment by JayVora-SerpentCS** [comment]
is this good to merge?

**Comment by AnuKPatel** [comment]
Let me review it, I will add Label of Ready to merge once I will review the PR. @JayVora-SerpentCS

**Pull request merged**
