### PR TITLE
made improvements in school transport module

### PR DESCRIPTION
**Pull request by Arpit-SerpentCS**

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
@AnuKPatel Do review

**Comment by JayVora-SerpentCS** [comment]
@Arpit-SerpentCS fix travis plz

**Comment by JayVora-SerpentCS** [comment]
fix travis plz

**Comment by murtuzasaleh** [comment]
@Arpit-SerpentCS Improve the README.rst file of a module. https://github.com/Arpit-SerpentCS/OdooEduERP/blob/11.0_schooltransport/school_transport/README.rst

**Comment by murtuzasaleh** [comment]
@Arpit-SerpentCS Please remove `hr` and `account` from dependency. https://github.com/Arpit-SerpentCS/OdooEduERP/blob/11.0_schooltransport/school_transport/__manifest__.py#L12

**Comment by murtuzasaleh** [comment]
@Arpit-SerpentCS Please add active_id inside the browse method. https://github.com/Arpit-SerpentCS/OdooEduERP/blob/11.0_schooltransport/school_transport/wizard/terminate_reason.py#L15

**Comment by murtuzasaleh** [comment]
@Arpit-SerpentCS Remove line no 4 and add `_` in line no 3. https://github.com/Arpit-SerpentCS/OdooEduERP/blob/11.0_schooltransport/school_transport/wizard/transfer_vehicle.py#L4

**Comment by murtuzasaleh** [comment]
@Arpit-SerpentCS Remove line no 8 and add it in line no 7. https://github.com/Arpit-SerpentCS/OdooEduERP/blob/11.0_schooltransport/school_transport/models/transport.py#L8

**Comment by murtuzasaleh** [comment]
@Arpit-SerpentCS Please add this portion in line no 64 https://github.com/Arpit-SerpentCS/OdooEduERP/blob/11.0_schooltransport/school_transport/models/transport.py#L71, L72, L73

class TransportVehicle(models.Model):
    '''for vehicle detail'''
    _name = 'transport.vehicle'
    _rec_name = 'vehicle'
    _description = 'Transport vehicle Information'

**Comment by murtuzasaleh** [comment]
@Arpit-SerpentCS Add directly in line no L425 https://github.com/Arpit-SerpentCS/OdooEduERP/blob/11.0_schooltransport/school_transport/models/transport.py#L424

Exa.:-mon1 = relativedelta(months=+rec.for_month)

**Comment by murtuzasaleh** [comment]
@Arpit-SerpentCS Please improved list name. https://github.com/Arpit-SerpentCS/OdooEduERP/blob/11.0_schooltransport/school_transport/models/transport.py#L445, L458, L465

Exa.:- vehi_participants_list, transport_list, trans_participants_list

**Comment by Arpit-SerpentCS** [comment]
@murtuzasaleh Please review the changes. Made improvements and tested the code according to the comments.

cc @JayVora-SerpentCS

**Pull request merged**
