### PR TITLE
made improvements in school module

### PR DESCRIPTION
**Pull request by Arpit-SerpentCS**

### CODE REVIEW

**Comment by murtuzasaleh** [comment]
@Arpit-SerpentCS Improve the README.rst file of a module. https://github.com/Arpit-SerpentCS/OdooEduERP/blob/11.0_school/school/README.rst

**Comment by murtuzasaleh** [comment]
@Arpit-SerpentCS Please add domain inside the search condition. https://github.com/Arpit-SerpentCS/OdooEduERP/blob/11.0_school/school/wizard/move_standards.py#L29

**Comment by murtuzasaleh** [comment]
@Arpit-SerpentCS Please add active_id inside the browse method. https://github.com/Arpit-SerpentCS/OdooEduERP/blob/11.0_school/school/wizard/teriminate_reason.py#L19

Use `user.active = False` https://github.com/Arpit-SerpentCS/OdooEduERP/blob/11.0_school/school/wizard/teriminate_reason.py#L29

**Comment by murtuzasaleh** [comment]
@Arpit-SerpentCS No need of data if noupdate="0". https://github.com/Arpit-SerpentCS/OdooEduERP/blob/11.0_school/school/security/school_security.xml#L4

**Comment by murtuzasaleh** [comment]
@Arpit-SerpentCS Please add domain inside the search view. https://github.com/Arpit-SerpentCS/OdooEduERP/blob/11.0_school/school/models/school.py#L224

**Comment by murtuzasaleh** [comment]
@Arpit-SerpentCS Both are char fields, IMO no need for str function. https://github.com/Arpit-SerpentCS/OdooEduERP/blob/11.0_school/school/models/teacher.py#L146

**Comment by Arpit-SerpentCS** [comment]
@murtuzasaleh Made improvements and tested the code according to comments.

cc @JayVora-SerpentCS

**Pull request merged**
